<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("description", "Сравни выбранные товары Керхер");
$APPLICATION->SetPageProperty("keywords", "Сравнение моделей техники Керхер");
$APPLICATION->SetPageProperty("title", "Сравнение моделей Karcher");
$APPLICATION->SetTitle("Сравнение товаров");
?><?$APPLICATION->IncludeComponent(
	"bitrix:catalog.compare.result", 
	"technoraum", 
	array(
		"ACTION_VARIABLE" => "action",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BASKET_URL" => "/personal/cart/",
		"CONVERT_CURRENCY" => "N",
		"DETAIL_URL" => "",
		"DISPLAY_ELEMENT_SELECT_BOX" => "N",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD_BOX" => "name",
		"ELEMENT_SORT_FIELD_BOX2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER_BOX" => "asc",
		"ELEMENT_SORT_ORDER_BOX2" => "desc",
		"FIELD_CODE" => array(
			0 => "ID",
			1 => "NAME",
			2 => "PREVIEW_TEXT",
			3 => "PREVIEW_PICTURE",
			4 => "DETAIL_TEXT",
			5 => "DETAIL_PICTURE",
			6 => "DATE_ACTIVE_FROM",
			7 => "DATE_ACTIVE_TO",
		),
		"HIDE_NOT_AVAILABLE" => "N",
		"IBLOCK_ID" => "8",
		"IBLOCK_TYPE" => "catalog",
		"NAME" => "CATALOG_COMPARE_LIST",
		"OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"PRICE_CODE" => array(
			0 => "price",
		),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_ID_VARIABLE" => "id",
		"PROPERTY_CODE" => array(
			0 => "PROIZVODITEL",
			1 => "TIP_UBORKI",
			2 => "POWER_PAR",
			3 => "DAVLENIE",
			4 => "POWER",
			5 => "PERFORMENCE",
			6 => "PARAMETRY_EHLEKTROSETI",
			7 => "AVTONOMNYJ",
			8 => "CLEANING_AREA",
			9 => "MOSHCHOST_VSASYVANIYA",
			10 => "MAX_POTREBLYAEMAYA_MOSHCHNOST",
			11 => "PROIZVODITELNOST",
			12 => "SOVMESTIMAYA_TEKHNIKA",
			13 => "ARTICLE",
			14 => "VREMYA_ZARYADKI_AKKUMULYATURA_MIN",
			15 => "PROF_PYLESOS",
			16 => "A_PYLESOSA",
			17 => "CHARACTERISTIC",
			18 => "SHIRINA_NASADOK",
			19 => "APPLICATION",
			20 => "COMPLETE_PAR",
			21 => "KOMPLEKTACIYA_AVD",
			22 => "COMPLETE",
			23 => "",
		),
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SHOW_PRICE_COUNT" => "1",
		"TEMPLATE_THEME" => "blue",
		"USE_PRICE_COUNT" => "N",
		"COMPONENT_TEMPLATE" => "technoraum",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO"
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>